Repository ynput/ayon-deadline, pull requests merged in 2024-09, with the labels that each got.

#31 Add USD pinning environments to submitters
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
Labels: type: feature

#34 Chore: More strict ruff
  client/ayon_deadline/addon.py
  client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
  client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
  client/ayon_deadline/plugins/publish/unreal/submit_unreal_deadline.py
  client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.py
  client/ayon_deadline/repository/custom/plugins/UnrealEngine5/UnrealEngine5.py
  ruff.toml
  server/settings/publish_plugins.py
Labels: type: maintenance

#35 Collect server url: Access server info correctly
  client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py
Labels: type: bug, community

#36 Publish jobs respect staging mode
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Labels: type: bug
