Repository ynput/ayon-deadline, pull requests merged in 2024-10, with the labels that each got.

#37 Remove `OpenPypeTileAssembler`
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
  client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.ico
  client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.options
  client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.param
  client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
  server/settings/publish_plugins.py
Labels: type: maintenance

#32 Allow job environment variable to be specified via context or instance
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/lib.py
  client/ayon_deadline/plugins/publish/aftereffects/submit_aftereffects_deadline.py
  client/ayon_deadline/plugins/publish/blender/submit_blender_deadline.py
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
  client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
  client/ayon_deadline/plugins/publish/global/collect_usd_pinning_env_vars.py
  client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  client/ayon_deadline/plugins/publish/max/submit_max_deadline.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
  client/ayon_deadline/plugins/publish/unreal/submit_unreal_deadline.py
Labels: type: enhancement, community

#38 Support `LimitGroups` and `MachineLimit` Houdini Deadline
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  server/settings/publish_plugins.py
Labels: type: enhancement, sponsored

#52 Review: Don't pass ftrack family to jobs
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  server/settings/publish_plugins.py
Labels: type: enhancement

#42 Submit AYON_SERVER_URL to jobs
  client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
  client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.param
  client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
  server/settings/publish_plugins.py
Labels: type: enhancement, bump minor
