Repository ynput/ayon-deadline, pull requests merged in 2024-11, with the labels that each got.

#56 Refactor Fusion submitter + minor code cosmetic changes
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Labels: type: enhancement

#49 Refactor Deadline Submission JobInfo
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/addon.py
  client/ayon_deadline/lib.py
  client/ayon_deadline/plugins/publish/aftereffects/submit_aftereffects_deadline.py
  client/ayon_deadline/plugins/publish/blender/submit_blender_deadline.py
  client/ayon_deadline/plugins/publish/celaction/submit_celaction_deadline.py
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
  client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  client/ayon_deadline/plugins/publish/global/collect_pools.py
  client/ayon_deadline/plugins/publish/global/submit_publish_cache_job.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_jobinfo.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_pools.py
  client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  client/ayon_deadline/plugins/publish/max/submit_max_deadline.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
  client/ayon_deadline/plugins/publish/unreal/submit_unreal_deadline.py
  package.py
  server/settings/publish_plugins.py
Labels: type: enhancement, bump minor

#62 Houdini: Set frames if cache instance has multiple frames
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
Labels: type: bug, sponsored

#67 Chore: Don't override already set env variables
  client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
Labels: type: enhancement

#66 Reduce submit publish job plugin filters
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/plugins/publish/houdini/submit_publish_cache_job.py
Labels: type: enhancement
