Repository ynput/ayon-deadline, pull requests merged in 2024-07, with the labels that each got.

#7 Add missing settings category
  client/ayon_deadline/plugins/publish/submit_aftereffects_deadline.py
  client/ayon_deadline/plugins/publish/validate_expected_and_rendered_files.py
Labels: bug

#6 Register host-specific Deadline plugins only on install of the host
  client/ayon_deadline/addon.py
  client/ayon_deadline/plugins/publish/aftereffects/submit_aftereffects_deadline.py
  client/ayon_deadline/plugins/publish/blender/submit_blender_deadline.py
  client/ayon_deadline/plugins/publish/celaction/submit_celaction_deadline.py
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
  client/ayon_deadline/plugins/publish/global/collect_deadline_server_from_instance.py
  client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py
  client/ayon_deadline/plugins/publish/global/collect_pools.py
  client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
  client/ayon_deadline/plugins/publish/global/help/validate_deadline_connection.xml
  client/ayon_deadline/plugins/publish/global/help/validate_deadline_pools.xml
  client/ayon_deadline/plugins/publish/global/submit_publish_cache_job.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_connection.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_pools.py
  client/ayon_deadline/plugins/publish/global/validate_expected_and_rendered_files.py
  client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_cache_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  client/ayon_deadline/plugins/publish/max/submit_max_deadline.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: enhancement

#13 Houdini Fix getting group name in DL submission
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
Labels: type: bug, sponsored

#15 Do not fail job on error in GlobalJobPreLoad
  client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: enhancement
