Repository ynput/ayon-deadline, pull requests merged in 2025-02, with the labels that each got.

#120 Do not update expected files if custom staging dir
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: bug, sponsored

#122 AE Submit job: Fix method signature
  client/ayon_deadline/plugins/publish/aftereffects/submit_aftereffects_deadline.py
Labels: type: bug

#121 Ensure that SSL verification setting is respected by all plugins.
  client/ayon_deadline/addon.py
  client/ayon_deadline/lib.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_connection.py
  client/ayon_deadline/plugins/publish/global/validate_deadline_pools.py
Labels: type: enhancement

#123 Chore: Add dependency on applications addon
  package.py
Labels: type: enhancement

#125 Fix: product ending with _1 confuses expected files validator
  client/ayon_deadline/plugins/publish/global/validate_expected_and_rendered_files.py
Labels: type: bug, sponsored

#124 Chore: Use 'AYON_USE_STAGING'
  client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: enhancement

#130 Fix: remove trailing slash in host url
  client/ayon_deadline/addon.py
Labels: type: bug, community

#131 Added possibility to control state of Publish job in Settings and Publisher UI
  client/ayon_deadline/lib.py
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/plugins/publish/houdini/submit_publish_cache_job.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
  server/settings/publish_plugins.py
Labels: type: bug, sponsored

#127 Fix logging correct default `ayon_server_url` in the logged message
  client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.param
  client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.py
  client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: bug

#132 Add default for `publish_job_state`
  server/settings/publish_plugins.py
Labels: type: bug

#133 Publish job: Ignore unfilled output dir
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Labels: type: enhancement, sponsored

#136 Added missing argument for blender
  client/ayon_deadline/plugins/publish/blender/submit_blender_deadline.py
Labels: type: bug

#135 Fix: passing of JobDelay and Machine list is a Deny
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  server/settings/publish_plugins.py
Labels: type: bug

#137 Version on context could be optional
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Labels: type: bug, sponsored

#138 Fix: if no profiles for CollectJobInfo found
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Labels: type: bug, sponsored
