Repository ynput/ayon-deadline, pull requests merged in 2025-01, with the labels that each got.

#99 Fix names of render jobs for Nuke
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: bug

#104 Fix Collect Job Info Groups and Limit Groups
  client/ayon_deadline/addon.py
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Labels: type: bug

#102 Fix Maya submit strict error checking and tile priority attributes
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
Labels: type: bug

#105 Updated ChunkSize for baking jobs to 999999
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: bug, sponsored

#91 Harmony: Render to workdir instead of publish dir
  client/ayon_deadline/plugins/publish/harmony/submit_harmony_deadline.py
Labels: type: enhancement

#95 Chore: Add submit api functions
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/addon.py
  client/ayon_deadline/constants.py
  client/ayon_deadline/lib.py
  client/ayon_deadline/plugins/publish/global/collect_deadline_server_from_instance.py
  client/ayon_deadline/plugins/publish/global/collect_default_deadline_server.py
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
  client/ayon_deadline/plugins/publish/global/validate_expected_and_rendered_files.py
  client/ayon_deadline/plugins/publish/houdini/submit_houdini_render_deadline.py
  client/ayon_deadline/plugins/publish/houdini/submit_publish_cache_job.py
  client/ayon_deadline/plugins/publish/maya/submit_maya_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: enhancement

#86 Fusion: Fix submission of multiple fusion render instances
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
Labels: type: bug

#107 Update setting default value for deadline dict on instance
  client/ayon_deadline/plugins/publish/global/collect_deadline_server_from_instance.py
Labels: type: bug

#110 Added overrides for 2D DCC in Collect JobInfo
  server/settings/publish_plugins.py
Labels: type: bug

#114 Chore/update logging wrong json
  client/ayon_deadline/abstract_submit_deadline.py
Labels: type: enhancement

#115 Publish UI populates pools from server settings
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
Labels: type: bug

#108 Job Info Output Directory+Files pass sequence and remap to published workfile if needed
  client/ayon_deadline/abstract_submit_deadline.py
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: bug, sponsored

#117 Settings: Change settings attributes in submit publish job plugin
  server/settings/publish_plugins.py
Labels: type: enhancement

#118 Fix assignment of job dependency
  client/ayon_deadline/plugins/publish/nuke/submit_nuke_deadline.py
Labels: type: bug, sponsored

#119 Added logging for location of metadata.json
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Labels: type: enhancement
