Repository ynput/ayon-deadline, pull requests merged in 2025-03, with the labels that each got.

#141 Support farm submissions for `image` product type
  client/ayon_deadline/plugins/publish/fusion/submit_fusion_deadline.py
Labels: type: bug, community

#145 Unreal submit: Make sure args are correct
  client/ayon_deadline/plugins/publish/unreal/submit_unreal_deadline.py
Labels: type: bug

#148 Make `Collect Deadline User Credentials` run on all hosts
  client/ayon_deadline/plugins/publish/global/collect_user_credentials.py
Labels: type: enhancement

#151 Write `version` into the publish job metadata if version is 0
  client/ayon_deadline/plugins/publish/global/submit_publish_job.py
Labels: type: bug, community

#154 Settings: Improve publish plug-ins labels and settings
  server/settings/publish_plugins.py
Labels: type: enhancement

#157 Chore: Add some type hints to `AbstractSubmitDeadline.__init__`
  client/ayon_deadline/abstract_submit_deadline.py
Labels: type: enhancement

#162 Removed host specific filter
  client/ayon_deadline/plugins/publish/global/validate_deadline_connection.py
Labels: type: bug

#164 Allow `concurrent_tasks` as exposed override in publisher UI for Collect Job Info
  client/ayon_deadline/plugins/publish/global/collect_jobinfo.py
  server/settings/publish_plugins.py
Labels: type: enhancement, sponsored

#165 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
